name: First Workflow
on: workflow_dispatch
jobs: 
  first-job:
    run-on: ubuntu-latest
    steps: 
      -name: Print Greeting
      run:  echo "Hello World"
      -name: Print Good By
      run: echo "Done -bye"
       